[package]
name = "it8951-video"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
bincode = "1.3.3"
ffmpeg-next = "5.1.1"
rusb = "0.9.1"
serde = { version = "1.0.147", features = ["derive"] }
structopt = "0.3.26"
tokio = { version = "1.21.2", features = ["full"] }
